### ISSUE TITLE
Wrong display of upcoming events

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/Fixometer#108]
There's two possibly related problems:

- Ordering of upcoming events is not chronologically consistent in the group page. For instance:
https://therestartproject.org/groups/restart-hq-2/
https://therestartproject.org/groups/restarters-leicester/

- For the Restart HQ group, the event showed in groups' page as coming up next is not the one actually happening soonest. (the same problem doesn't seem to affect other groups with multiple upcoming events, such as Turin and Leicester) 
 https://therestartproject.org/groups/

Hi @IronRunes - I don't notice these problems occurring in the past, I wonder if they're related to anything else you've been working on recently, ie. timestamp?

**Comment by ngm** [comment]
@IronRunes - an extra piece of information here - at the time @ugomatic reported this, the 'Next Event' showing for Restart HQ on the group list was showing the Oct 2017 event.  Since reporting, the May 9th Brixton Pound event has been added - which may explain why this event now appears as the next event - could it be that the group list is always showing the most recently created event for a group?

**Comment by IronRunes** [comment]
@ngm to some extent that is relevant: the problem was within a (wrong) assumption (that events would be added in chronological order). I rewrote the WP_Query param list and it should be fixed now.
