### ISSUE TITLE
Party successfully created presents blank data entry screen 

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#190]
This is disconcerting as a user - after you fill in new party details, you get this screen. Ideally you would end up at the Parties list, or on the saved version of your party. 
![screen shot 2018-02-09 at 17 11 50](https://user-images.githubusercontent.com/4210588/36040259-d899d054-0dbc-11e8-918a-83c893a14403.png)

**Comment by ngm** [comment]
As discussed @NikhitaPaturu .

Some things to think about - the framework doesn't have a built-in system in place for temporary/flash messages.  The quick workaround for this is to append a query string parameter such as ?action=created and then check for this in the action method in order to determine if we should display a message on the page we redirected to.

**Comment by ngm** [comment]
* In PartyController create method we need to add an extra check to see if the user has the role 'Administrator'
* If they do, we should redirect to /admin?action=pc&code=200
* It looks as if AdminController index method already has the right checks in place to display the message.

**Comment by ngm** [comment]
Done, ready for release.
