### ISSUE TITLE
Unable to edit user data while logged in both as Admin and User

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/Fixometer#81]
Tried to change my JanetHost user data, while logged in as Admin - changes not saved. Same occurs when logged in as JanetHost.

**Comment by ngm** [comment]
Hi @IronRunes , any progress on this issue?

**Comment by ngm** [comment]
The issue may have been using the same email address as already in use for an existing account.  I could recreate this locally as per the image below.

![image](https://cloud.githubusercontent.com/assets/172324/24000604/94290a9c-0a53-11e7-8bc1-f2f3e0c486d5.png)

The best resolution to this issue would be trap the specific error and show the user a more error-specific error message.

i.e. in this case, rather than 'Something went wrong.  Please check the data and try again.', error would be 'The email address you have entered is already in use by another account.  Please use a different email address.'

Can you implement that @IronRunes ?

**Comment by IronRunes** [comment]
@ngm yes, this can be done.

**Comment by IronRunes** [comment]
ready to b tested @ngm

**Comment by ngm** [comment]
@IronRunes tested and works, thanks - please push to production

**Comment by IronRunes** [comment]
pushed
